// REGISTRATION
export const REGISTRATION_INPUT_CHANGE = 'REGISTRATION_INPUT_CHANGE';
export const REGISTRATION_FORM_SUCCESS = 'REGISTRATION_FORM_SUCCESS';
export const REGISTRATION_FORM_LOADING = 'REGISTRATION_FORM_LOADING';
export const REGISTRATION_FORM_ERROR = 'REGISTRATION_FORM_ERROR';

// LOGIN
export const LOGIN_INPUT_CHANGE = 'LOGIN_INPUT_CHANGE';
export const LOGIN_FORM_SUCCESS = 'LOGIN_FORM_SUCCESS';
export const LOGIN_FORM_LOADING = 'LOGIN_FORM_LOADING';
export const LOGIN_FORM_ERROR = 'LOGIN_FORM_ERROR';
export const LOGOUT = 'LOGOUT';

// TEMPLATES
export const TEMPLATES_FETCH = 'TEMPLATES_FETCH';
export const TEMPLATES_ERROR = 'TEMPLATES_ERROR';
export const TEMPLATES_LOADING = 'TEMPLATES_LOADING';
export const TEMPLATES_CREATE = 'TEMPLATES_CREATE';
export const TEMPLATES_DELETE = 'TEMPLATES_DELETE';
export const TEMPLATES_ADD_EXERCISE = 'TEMPLATES_ADD_EXERCISE';
export const TEMPLATES_DELETE_EXERCISE = 'TEMPLATES_DELETE_EXERCISE';
export const TEMPLATES_SAVED = 'TEMPLATES_SAVED';

// EXERCISES
export const EXERCISES_CREATE = 'EXERCISES_CREATE';
export const LOAD_EXERCISES = 'LOAD_EXERCISES';

// WORKOUT
export const START_WORKOUT = 'START_WORKOUT';
export const ADD_SET = 'ADD_SET';
export const DELETE_SET = 'DELETE_SET';
export const FINISH_WORKOUT = 'FINISH_WORKOUT';
export const WORKOUT_ERROR = 'WORKOUT_ERROR';
export const LOAD_WORKOUT_NAME = 'LOAD_WORKOUT_NAME';
// export const ON_MOOD_CHANGE = 'ON_MOOD_CHANGE';
